openapi: '3.0.2'
info:
  title: Proves de yaml
  version: '1.0'
servers:
  - url: https://api.server.test/v1

paths:
  /test:
    get:
      description: Summary del get de test
      responses:
        '200':
          description: Descripcio de reposta 200 de get de /test
  /prova:
    get:
      description: Summary del get de prova
      responses:
        '200':
          description: Descripcio de reposta 200 de get de /prova
        '400':
          description: Descripcio de reposta 400 de get de /prova
        '500':
          description: Error de servidor
  