openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1

paths:
  /test:
    get:
      responses:
        '200':
          description: descripcio de reposta 200 de get de /test

  /prova:
    get:
      responses:
        '200':
          description: descripcio de reposta 200 de get de /prova
        '400':
          description: descripcio de reposta 400 de get de /prova
  
          