openapi: '3.0.3'
info:
  version: '1.0.0'
  title: API Ships Departures info
  description: 
    Vessels that have sailed up or are sailing up today.  
  license:
    name: CC0 1.0 Universal (CC0 1.0)
    url: https://creativecommons.org/publicdomain/zero/1.0/deed.es
  contact:
    name: OpenInfoAPI github
    url: https://github.com/portdebarcelona/OpenInfoAPI-Ports
tags:
  - name: Vessels that have sailed up or are sailing up today.
    description: "Vessels that have sailed up or are sailing up today."
servers:
  - url: https://api.server.test/v1
paths:
  /departures:
    get:
      summary: Returns a list of ships that have departed or will depart today from a port. 
      description: Returns a list of ships that have departed or will depart today from a port.
      parameters:
        - $ref: '#/components/parameters/portCode'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            API-Version:
              $ref: './oiapComponents.yml#/components/headers/API-Version'
            Current-Page:
              $ref: './oiapComponents.yml#/components/headers/Current-Page'
            Next-Page:
              $ref: './oiapComponents.yml#/components/headers/Next-Page'
            Prev-Page:
              $ref: './oiapComponents.yml#/components/headers/Prev-Page'
            Last-Page:
              $ref: './oiapComponents.yml#/components/headers/Last-Page'
            First-Page:
              $ref: './oiapComponents.yml#/components/headers/First-Page'
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/shipDepartures'
        default:
          description: Unexpected error
          headers:
            API-Version:
              $ref: './oiapComponents.yml#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'                
components:
  parameters: 
    ##################
    # Query parameters
    ##################
    portCode:
      in: query
      name: portCode
      description: |
            Port UN/LOCODE
            Default value is Locode of Port what provides the services
            example: portCode=ESBCN        
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/portCode'
    shipType:
      in: query
      name: shipType
      description:
            Type of ship 
            Default value are all types
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/shipType'
  schemas: 
    shipDepartures:
      description: list of ships that have departed or will depart today
      type: object
      allOf:
        - type: object
          properties:
            shipIMONumber:
              $ref: './oiapComponents.yml#/components/schemas/shipIMONumber'
        - type: object
          properties:
            shipName:
              $ref: './oiapComponents.yml#/components/schemas/shipName'
        - type: object
          properties:
            shipType:
              $ref: './oiapComponents.yml#/components/schemas/shipType'
        - type: object
          properties:
            actualTimeOfDeparture:
              $ref: './oiapComponents.yml#/components/schemas/actualTimeOfDeparture'
        - type: object
          properties:
            estimatedTimeOfDeparture:
              $ref: './oiapComponents.yml#/components/schemas/estimatedTimeOfDeparture'
        - type: object
          properties:
            nextPortOfCall:
              $ref: './oiapComponents.yml#/components/schemas/nextPortOfCall'
        - type: object
          properties:
            berth:
              $ref: './oiapComponents.yml#/components/schemas/berth'
      required: 
        - shipIMONumber
        - shipName
        - shipType
        - estimatedTimeOfDeparture
        - berth
