openapi: '3.0.3'
info:
  version: '0.9.0-oas3'
  title: OIAP
  description: |
    **Open Info API para Puertos**

    This file is a copy of 14oiapPortCalendar.yml for testing the use of $ref to retrieve schemas with files that are not openapi compliant. 

    This file contains all the APIs developed for the `Open Info API para Puertos` project for the **Port Calendar Domain** within the initiative Ports 4.0 form Puertos del Estado (ES).

  termsOfService: http://swagger.io/terms/
  license:
    name: CC0 1.0 Universal (CC0 1.0)
    url: https://creativecommons.org/publicdomain/zero/1.0/deed.es
  contact:
    name: OpenInfoAPI github
    url: https://github.com/portdebarcelona/OpenInfoAPI-Ports
tags:
  - name: Port Calendar
    description: "APIs related to the calendar in a port."
    externalDocs:
      description: Description 
      url: http://swagger.io/ 
servers:
  - url: https://raw.githubusercontent.com/portdebarcelona/OpenInfoAPI-Ports/develop/oasdefinitions
    description: >
        Main server 
paths:
  /holidays:
    get:
      tags:
        - Port Calendar
      summary: Returns a list of holidays in a given period of time of a year and for a given place.
      description: Information about list of public holidays from a requested period of time of a year and a place (country and subdivision).
      parameters:
        - $ref: '#/components/parameters/country'
        - $ref: '#/components/parameters/subdivision'
        - $ref: '#/components/parameters/portCode'
        - $ref: '#/components/parameters/fromDate' 
        - $ref: '#/components/parameters/toDate'       
      responses: #status code
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './testOiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  holidays:
                    type: array
                    items:
                      $ref: '#/components/schemas/holiday'
                  metadata:
                        $ref: './testOiapComponents.yml#/components/schemas/metadata'                  
                  queryParams:
                    type: object
                    properties:
                      country:
                        $ref: './testOiapComponents.yml#/components/schemas/countryCode'
                      subdivision:
                        $ref: './testOiapComponents.yml#/components/schemas/subdivisionCode'
                      portCode:
                        $ref: './testOiapComponents.yml#/components/schemas/portCode'
                      fromDate:
                        $ref: './testOiapComponents.yml#/components/schemas/fromDate'
                      toDate:
                        $ref: './testOiapComponents.yml#/components/schemas/toDate'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './testOiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './testOiapComponents.yml#/components/schemas/error' 

components:
  parameters: 

    country:
      in: query
      name: country
      description: ISO3166 2 characters country code.        
      required: false
      style: form
      explode: false
      schema:
        $ref: './testOiapComponents.yml#/components/schemas/countryCode'

    subdivision:
      in: query
      name: subdivision
      description: ubdivision code from ISO 3166 — Codes for the representation of names of countries and their subdivisions.         
      required: false
      style: form
      explode: false
      schema:
        $ref: './testOiapComponents.yml#/components/schemas/subdivisionCode'

    portCode:
      in: query
      name: portCode
      description: |
            Port UN/LOCODE
            Default value is Locode of Port what provides the services
            example: portCode=ESBCN        
      required: false
      style: form
      explode: false
      schema:
        $ref: './testOiapComponents.yml#/components/schemas/portCode'

    fromDate:
      in: query
      name: fromDate
      description: First day of a period, expressed as YYYY-MM-DD.        
      required: false
      style: form
      explode: false
      schema:
        $ref: './testOiapComponents.yml#/components/schemas/fromDate'

    toDate:
      in: query
      name: toDate
      description: Last day of a period, expressed as YYYY-MM-DD.        
      required: false
      style: form
      explode: false
      schema:
        $ref: './testOiapComponents.yml#/components/schemas/toDate'

  schemas:
    holiday:
      description: 'A day on which normal activities, especially business or work including school, are suspended or reduced.'
      type: object
      allOf:
        - type: object 
          properties:
            holidayDate:  
              $ref: './testOiapComponents.yml#/components/schemas/holidayDate'
            holidayType: 
              $ref: './testOiapComponents.yml#/components/schemas/holidayType'
            holidayCountry:
              $ref: './testOiapComponents.yml#/components/schemas/countryCode'
            holidaySubdivision:
              $ref: './testOiapComponents.yml#/components/schemas/subdivisionCode'
            holidayPort:
              $ref: './testOiapComponents.yml#/components/schemas/portCode'
      required:
        - holidayDate

