openapi: '3.0.3'
info:
  version: '0.9.0-oas3'
  title: OIAP
  description: |
    **Open Info API para Puertos**


    This file contains all the APIs developed for the `Open Info API para Puertos` project for the **Liner Services Domain** within the initiative Ports 4.0 form Puertos del Estado (ES). 

  termsOfService: http://swagger.io/terms/
  license:
    name: CC0 1.0 Universal (CC0 1.0)
    url: https://creativecommons.org/publicdomain/zero/1.0/deed.es
  contact:
    name: OpenInfoAPI github
    url: https://github.com/portdebarcelona/OpenInfoAPI-Ports
tags:
  - name: Liner Services
    description: "APIs related to the Liner Services that are scheduled in a port."
    externalDocs:
      description: Description 
      url: http://swagger.io/ # https://raw.githubusercontent.com/portdebarcelona/OpenInfoAPI-Ports/develop/docs/CatalogIntroduction.md It must be a link to a GitHub file with a more extensive description like Liner Services are those served by liner ships that regularly sails on a fixed route following a schedule. A shipping schedule can be checked by vessel, by port of call, or by routing. 
servers:
  - url: https://raw.githubusercontent.com/portdebarcelona/OpenInfoAPI-Ports/develop/oasdefinitions
    description: Servidor server 
# Canvi efectuat: 'https://raw.githubusercontent.com/portdebarcelona/OpenInfoAPI-Ports/develop/oasdefinitions a '.

# Afegir un get de terminals ferroviaries del port
# Amb quines terminals tenim connexions
paths:
  /linerServices:
    get:
      tags:
        - Liner Services
      summary: Returns a list of liner services of a port.
      description: Returns a list of liner services of a port. 
      parameters:
        - $ref: '#/components/parameters/portCode'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  linerService:
                    type: array
                    items:
                      $ref: '#/components/schemas/linerService'
                  requestedParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'  
  /linkedPorts:
    get:
      tags:
        - Liner Services
      summary: Returns the list of linked ports served by liner services from a port. 
      description: >-
        This GET API returns the list of linked ports served by liner services from a port. 
      parameters:
        - $ref: '#/components/parameters/portCode'
        - $ref: '#/components/parameters/geographicalZone'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  linkedPorts:
                    type: array
                    items:
                      $ref: '#/components/schemas/linkedPort'
                  requestedParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
                      geographicalZone:
                        $ref: './oiapComponents.yml#/components/schemas/geographicalZone'                        
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
  /linerCarriers: 
    get:
      tags:
        - Liner Services
      summary: List of the carriers that serve a liner service or a geographical area.
      description: Returns a list of the carriers and alliance partners that serve a particular liner service or a geographical area.
      parameters:
        - $ref: '#/components/parameters/portCode'
        - $ref: '#/components/parameters/linerServiceName'
        - $ref: '#/components/parameters/geographicalZone'        
      responses: #status code
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  linerCarriers:
                    type: array
                    items:
                      $ref: '#/components/schemas/linerCarrier'
                  requestedParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
                      linerServiceName:
                        $ref: './oiapComponents.yml#/components/schemas/linerServiceName'
                      geographicalZone:
                        $ref: './oiapComponents.yml#/components/schemas/geographicalZone'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'
components:
  parameters: 
    portCode:
      in: query
      name: portCode
      description: |
            Port UN/LOCODE
            Default value is Locode of Port what provides the services
            example: portCode=ESBCN        
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/portCode'
    geographicalZone:  
      in: query
      name: geographicalZone
      description: 
            Geographical area represented a a code defined in the Geonomenclature docummentation from EUROSTAT.
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/geographicalZone'
    linerServiceName:  
      in: query
      name: fromDate
      description: 
            The name of a Liner Service as it is in Alphaliner.
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/linerServiceName'
  schemas:
    linerService: # Important definir aquesta estructura de dades.
      description: 'List of attributes that describe a liner service.'
      type: object
      allOf:
        - type: object
          properties:
            linerServiceName:  
              $ref: './oiapComponents.yml#/components/schemas/linerServiceName' 
            linerServiceCode:  # alphaliner code
              $ref: './oiapComponents.yml#/components/schemas/linerServiceCode'
            linerPartners: 
              $ref: '#/components/schemas/linerPartners'        
            linerSlots:
              $ref: '#/components/schemas/linerSlots' 
            coveredGeographicalAreas:  
              $ref: '#/components/schemas/coveredGeographicalAreas' 
            linerServiceType:  
              $ref: './oiapComponents.yml#/components/schemas/linerServiceType'
            linerSailingFrequency:  
              $ref: './oiapComponents.yml#/components/schemas/linerSailingFrequency' 
            linerDurationOfRotation:  
              $ref: './oiapComponents.yml#/components/schemas/linerDurationOfRotation'
      required:
        - linerServiceName
        - linerPartners
        - coveredGeographicalAreas  
        - linerServiceType
        - linerSailingFrequency  
    linerPartners:
      description: 'Shipping lines that share vessels for a liner service.'
      type: array
      items:
        $ref: './oiapComponents.yml#/components/schemas/linerPartner'
    linerSlots: # millorar descripcio
      description: 'Shipping lines that have slots of a liner service.'
      type: array
      items:
        $ref: './oiapComponents.yml#/components/schemas/linerSlot'
    coveredGeographicalAreas:
      description: 'Geographical area covered by a liner service.'
      type: array
      items:
        $ref: './oiapComponents.yml#/components/schemas/geographicalZone'
    linkedPort: # PENDENT definir aquesta estructura de dades.
      description: ''
      type: object
      allOf:
        - type: object
          properties:
            locode:  
              $ref: './oiapComponents.yml#/components/schemas/locode' 
        - type: object
          properties:
            railTerminalCode:  
              $ref: './oiapComponents.yml#/components/schemas/railTerminalCode'  
        - type: object
          properties:
            railTerminalName: 
              $ref: './oiapComponents.yml#/components/schemas/railTerminalName' 
    linerCarrier: # Important definir aquesta estructura de dades.
      description: ''
      type: object
      allOf:
        - type: object
          properties:
            locode: 
              $ref: './oiapComponents.yml#/components/schemas/locode' 
        - type: object
          properties:
            railTerminalCode: 
              $ref: './oiapComponents.yml#/components/schemas/railTerminalCode'  
        - type: object
          properties:
            railTerminalName: 
              $ref: './oiapComponents.yml#/components/schemas/railTerminalName' 