openapi: '3.0.3'
info:
  version: '0.9.0-oas3'
  title: OIAP
  description: |
    **Open Info API para Puertos**


    This file contains all the APIs developed for the `Open Info API para Puertos` project for the **Port Infrastructure Domain** within the initiative Ports 4.0 form Puertos del Estado (ES). 

  termsOfService: http://swagger.io/terms/
  license:
    name: CC0 1.0 Universal (CC0 1.0)
    url: https://creativecommons.org/publicdomain/zero/1.0/deed.es
  contact:
    name: OpenInfoAPI github
    url: https://github.com/portdebarcelona/OpenInfoAPI-Ports
tags:
  - name: Port Infrastructure
    description: "APIs related to the infrastructures of a port."
    externalDocs:
      description: Description 
      url: http://swagger.io/ # https://raw.githubusercontent.com/portdebarcelona/OpenInfoAPI-Ports/develop/docs/CatalogIntroduction.md It must be a link to a GitHub file with a more extensive description like Port Infrastructure are those served by liner ships that regularly sails on a fixed route following a schedule. A shipping schedule can be checked by vessel, by port of call, or by routing. 
servers:
  - url: https://raw.githubusercontent.com/portdebarcelona/OpenInfoAPI-Ports/develop/oasdefinitions
    description: Servidor server 
# Canvi efectuat: 'https://raw.githubusercontent.com/portdebarcelona/OpenInfoAPI-Ports/develop/oasdefinitions a '.

paths:
  /portInfrastructure:
    get:
      tags:
        - Port Infrastructure
      summary: Returns a list of basic data of the infrastructure of a port.
      description: Returns a list of basic data of the infrastructure of a port. 
      parameters:
        - $ref: '#/components/parameters/portCode'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  portInfrastructure:
                    type: array
                    items:
                      $ref: '#/components/schemas/portInfrastructure'
                  requestedParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'  
  /portGates:
    get:
      tags:
        - Port Infrastructure
      summary: Information about the main land port accesses. 
      description: >-
        This GET API returns the list of port gates from a port. 
      parameters:
        - $ref: '#/components/parameters/portCode'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  portGates:
                    type: array
                    items:
                      $ref: '#/components/schemas/portGate'
                  requestedParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
  /berths: 
    get:
      tags:
        - Port Infrastructure
      summary: Information about the berths of a port
      description: List of the berths from a port.
      parameters:
        - $ref: '#/components/parameters/portCode'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  berths:
                    type: array
                    items:
                      $ref: './oiapComponents.yml#/components/schemas/berth'
                  requestedParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'
  /portTerminals: 
    get:
      tags:
        - Port Infrastructure
      summary: Information about the maritime terminals of a port
      description: List of the maritime terminals from a port.
      parameters:
        - $ref: '#/components/parameters/portCode'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  portTerminals:
                    type: array
                    items:
                      $ref: '#/components/schemas/portTerminal'
                  requestedParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
  /railTerminals: 
    get:
      tags:
        - Port Infrastructure
      summary: Information of all the rail terminals and loading tracks of a port
      description: >
          List of the rail terminals and loading tracks from a port.
          Rail facilities are caracterized because they have rail bundles of up to 10 rail tracks with lengths of a maximum of 800 meters per track. They are equipped to allow simultaneous batch exchanges (direct transshipment) through the use of rail-mounted gantry cranes that stretch over the rail bundles.
      parameters:
        - $ref: '#/components/parameters/portCode'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  railTerminals:
                    type: array
                    items:
                      $ref: '#/components/schemas/railTerminal' 
                  requestedParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'               
  /marineAids: 
    get:
      tags:
        - Port Infrastructure
      summary: Marine aids to navigation
      description: List of port marks in a specific port.
      parameters:
        - $ref: '#/components/parameters/portCode'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  portMarks:
                    type: array
                    items:
                      $ref: '#/components/schemas/portMark' 
                  requestedParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'     
  /bathymetry: 
    get:
      tags:
        - Port Infrastructure
      summary: Bathymetric data from channel and berths.
      description: Data from the regular hydrographic surveis that are being performed at ports.
      parameters:
        - $ref: '#/components/parameters/portCode'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  batymetry:
                    type: array
                    items:
                      $ref: '#/components/schemas/bathymetry' 
                  requestedParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'     
components:
  parameters: 
    portCode:
      in: query
      name: portCode
      description: |
            Port UN/LOCODE
            Default value is Locode of Port what provides the services
            example: portCode=ESBCN        
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/portCode'
  schemas:
    portInfrastructure:
      description: 'List of main attibutes from the infrastructure of a port.'
      type: object
      allOf:
        - type: object 
          properties:
            portName:  
              $ref: './oiapComponents.yml#/components/schemas/portName' 
            portCode: 
              $ref: './oiapComponents.yml#/components/schemas/portCode'
            portCoordinates:  
              $ref: './oiapComponents.yml#/components/schemas/coordinates'
            totalPortArea:
              $ref: './oiapComponents.yml#/components/schemas/totalArea'
            totalBerthLength:
              $ref: './oiapComponents.yml#/components/schemas/berthLength'
            totalCoveredWarehouses:
              $ref: './oiapComponents.yml#/components/schemas/coveredWarehouses'
      required:
        - portName 

    portGate: 
      description: 'Land access gates from a port.'
      type: object
      allOf:
        - type: object
          properties:
            gate:  
              $ref: './oiapComponents.yml#/components/schemas/gate'
      required:
        - gate 

    portTerminal: 
      description: 'Multifunctional logistics complex providing a full range of services for handling cargo.' 
      type: object
      allOf:
        - type: object
          properties:
            terminalName:  
              description: Terminal name.
              type: string
              example: Terminal Port Nou
            terminalCode:  
              description: 'IMO Port Facility Number. It consists of a five-character LOCODE corresponding to a port and a 4-digit code separated with a dash. Those codes can be retrieved in www.portcode.com' 
              type: string
              maxLength: 10 
              example: ESBCN-0036              
            totalArea: 
              $ref: './oiapComponents.yml#/components/schemas/totalArea'
            coveredWarehouses: 
              $ref: './oiapComponents.yml#/components/schemas/coveredWarehouses'
            terminalGates: 
              type: array
              items:
                $ref: './oiapComponents.yml#/components/schemas/gate'
            berths: 
              type: array
              items:
                $ref: './oiapComponents.yml#/components/schemas/berth'
      required:
        - terminalName 

    railTerminal: 
      description: >
          Attributes of a rail terminal facility.
      type: object
      allOf:
        - type: object
          properties:
            railTerminalName:  
              $ref: './oiapComponents.yml#/components/schemas/railTerminalName' 
            railTerminalCode:  
              $ref: './oiapComponents.yml#/components/schemas/railTerminalCode' 
            freightType: 
              $ref: './oiapComponents.yml#/components/schemas/freightType'
            coordinates: 
              $ref: './oiapComponents.yml#/components/schemas/coordinates'
            railBundles: 
              $ref: './oiapComponents.yml#/components/schemas/railBundles'
            trackMaximumLength: 
              $ref: './oiapComponents.yml#/components/schemas/trackMaximumLength'
            trackGauges: 
              type: array
              items:
                $ref: './oiapComponents.yml#/components/schemas/trackGauge'        
            gantryCranes: 
              $ref: './oiapComponents.yml#/components/schemas/gantryCranes'
      required:
        - railTerminalName 

    portMark: 
      description: 'Buoys, Beacons and Marks, according to the IALA Buoyage System that includes five buoy types: cardinal, lateral, isolated danger, special and safe water marks.' 
      type: object
      allOf:
        - type: object
          properties:
            markRegion:  
              $ref: './oiapComponents.yml#/components/schemas/markRegion'
            markType:  
              $ref: './oiapComponents.yml#/components/schemas/markType' 
            markTop: 
              $ref: './oiapComponents.yml#/components/schemas/markTop'
            markColour: 
              $ref: './oiapComponents.yml#/components/schemas/markColour'
            shapeOfBuoy: 
              $ref: './oiapComponents.yml#/components/schemas/shapeOfBuoy'
            markLight: 
              $ref: './oiapComponents.yml#/components/schemas/markLight'
            coordinates:
              $ref: './oiapComponents.yml#/components/schemas/coordinates'
      required:
        - linerServiceName 

    bathymetry: 
      description: 'Land access gates from a port.' 
      type: object
      allOf:
        - type: object
          properties:
            singularPoint:
              $ref: './oiapComponents.yml#/components/schemas/singularPoint'                  
            underwaterDepth: 
              $ref: './oiapComponents.yml#/components/schemas/underwaterDepth'
      required:
        - linerServiceName 



