openapi: '3.0.3'
info:
  version: '0.9.0-oas3'
  title: OIAP
  description: |
    **Open Info API para Puertos**


    This file contains all the APIs developed for the `Open Info API para Puertos` project for the **Port Rates and Fees Domain** within the initiative Ports 4.0 form Puertos del Estado (ES).

  termsOfService: http://swagger.io/terms/
  license:
    name: CC0 1.0 Universal (CC0 1.0)
    url: https://creativecommons.org/publicdomain/zero/1.0/deed.es
  contact:
    name: OpenInfoAPI github
    url: https://github.com/portdebarcelona/OpenInfoAPI-Ports
tags:
  - name: Rates and Fees
    description: "APIs related to the docummentary procedures of a port."
    externalDocs:
      description: Description 
      url: http://swagger.io/ 
servers:
  - url: https://raw.githubusercontent.com/portdebarcelona/OpenInfoAPI-Ports/develop/oasdefinitions
    description: >
        Servidor server 


        The costs associated to the ship calls and  the flow of goods through ports must be published as part of a transparency policy of those ports.

        Bellow there is a summary of the rates applicable by a Spanish Port Authority:
        - Navigation Support Rate (T0)
        - Vessel Rate (T1)
        - Passenger Rate (T2)
        - Cargo Rate (T3)
        - Fresh fish Rate (T4)
        - Pleasure and Sports Craft Rate (T5)
        - Special Use of the Transit Zone Rate (T6)
        - Vessel-Generated Waste Collection Service Fee

        Possible APIs:
        - **Ship calls fees**: List of the port rates and fees associated to a ship call at a specific port.
          - Request parameters: port name, port UN/LOCODE.
          - Data included in the response: link to the port website where this information is published.
        - **Cargo fees**: List of the port rates and fees associated to the flow of goods at a specific port.
          - Request parameters: port name, port UN/LOCODE, email.
          - Data included in the response: link to the port website where this information is published.

paths:
  /basicTrafficEnvironment:
    get:
      tags:
        - Rates and Fees
      summary: Returns a list of resources where the procedures for clearing the goods in import can be found.
      description: Returns a list of resources where the procedures for clearing the goods in import can be found. 
      parameters:
        - $ref: '#/components/parameters/portCode'
      responses: 
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  basicTrafficEnvironment:
                    type: array
                    items:
                      $ref: '#/components/schemas/basicTrafficEnvironment'
                  queryParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/Error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/Error'  
  /basicEconomicData:
    get:
      tags:
        - Rates and Fees
      summary: Returns a list of resources where the procedures for clearing the goods subject to controls from the border inspection services can be found.
      description: Returns a list of resources where the procedures for clearing the goods subject to controls from the border inspection services can be found. 
      parameters:
        - $ref: '#/components/parameters/portCode'
      responses: 
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  basicEconomicData:
                    type: array
                    items:
                      $ref: '#/components/schemas/basicEconomicData'
                  queryParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/Error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/Error' 

 

components:
  parameters: 
    portCode:
      in: query
      name: portCode
      description: |
            Port UN/LOCODE
            Default value is Locode of Port what provides the services
            example: portCode=ESBCN        
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/portCode'


  schemas:
    basicTrafficEnvironment: 
      description: 'URI where a customs clearance procedure from a port can be found.'
      type: object
      allOf:
        - type: object 
          properties:
            customsClearanceDescription:  
              description: 'Procedure description'
              type: string
              enum: ['All .'] 
            customsClearanceUri:  
              $ref: './oiapComponents.yml#/components/schemas/uri' 
      required:
        - customsClearanceUri 

    basicEconomicData: 
      description: 'URI where a border inspection procedure from a port can be found.'
      type: object
      allOf:
        - type: object 
          properties:
            borderInspectionDescription:  
              description: 'Procedure description'
              type: string
              enum: ['The '] 
            borderInspectionUri:  
              $ref: './oiapComponents.yml#/components/schemas/uri' 
      required:
        - borderInspèctionUri 

