openapi: '3.0.3'
info:
  version: '0.9.0-oas3'
  title: OIAP
  description: |
    **Open Info API para Puertos**


    This file contains all the APIs developed for the `Open Info API para Puertos` project for the **Port Rates and Fees Domain** within the initiative Ports 4.0 form Puertos del Estado (ES).

  termsOfService: http://swagger.io/terms/
  license:
    name: CC0 1.0 Universal (CC0 1.0)
    url: https://creativecommons.org/publicdomain/zero/1.0/deed.es
  contact:
    name: OpenInfoAPI github
    url: https://github.com/portdebarcelona/OpenInfoAPI-Ports
tags:
  - name: Rates and Fees
    description: "APIs related to the port rates and fees."
    externalDocs:
      description: Description 
      url: http://swagger.io/ 
servers:
  - url: https://raw.githubusercontent.com/portdebarcelona/OpenInfoAPI-Ports/develop/oasdefinitions
    description: >
        Main server. 


        The costs associated to the ship calls and  the flow of goods through ports must be published as part of a transparency policy of those ports.

        Bellow there is a summary of the rates applicable by a Spanish Port Authority:
        - Navigation Support Rate (T0)
        - Vessel Rate (T1)
        - Passenger Rate (T2)
        - Cargo Rate (T3)
        - Fresh fish Rate (T4)
        - Pleasure and Sports Craft Rate (T5)
        - Special Use of the Transit Zone Rate (T6)
        - Vessel-Generated Waste Collection Service Fee

paths:
  /portRatesAndFees:
    get:
      tags:
        - Rates and Fees
      summary: Returns the URL of the website where rates and fees from a port are published. 
      description: Returns the URL of the website where rates and fees from a port are published.  
      parameters:
        - $ref: '#/components/parameters/portCode'
      responses: 
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  ratesAndFeesUrl:
                    type: array
                    items:
                      $ref: '#/components/schemas/ratesAndFeesUrl'
                  queryParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'  

components:
  parameters: 
    portCode:
      in: query
      name: portCode
      description: |
            Port UN/LOCODE
            Default value is Locode of Port what provides the services
            example: portCode=ESBCN        
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/portCode'

  schemas:
    ratesAndFeesUrl: 
      description: 'URI where a customs clearance procedure from a port can be found.'
      type: object
      allOf:
        - type: object 
          properties:
            ratesAndFeesUrl:  
              $ref: './oiapComponents.yml#/components/schemas/uri' 

