openapi: '3.0.3'
info:
  version: '0.9.0-oas3'
  title: OIAP
  description: |
    **Open Info API para Puertos**


    This file contains all the APIs developed for the `Open Info API para Puertos` project for the **Port Calendar Domain** within the initiative Ports 4.0 form Puertos del Estado (ES).

  termsOfService: http://swagger.io/terms/
  license:
    name: CC0 1.0 Universal (CC0 1.0)
    url: https://creativecommons.org/publicdomain/zero/1.0/deed.es
  contact:
    name: OpenInfoAPI github
    url: https://github.com/portdebarcelona/OpenInfoAPI-Ports
tags:
  - name: Port Calendar
    description: "APIs related to the docummentary procedures of a port."
    externalDocs:
      description: Description 
      url: http://swagger.io/ 
servers:
  - url: https://raw.githubusercontent.com/portdebarcelona/OpenInfoAPI-Ports/develop/oasdefinitions
    description: Servidor server 

paths:
  /portCalendar:
    get:
      tags:
        - Port Calendar
      summary: Returns a list of working days and openning hours.
      description: >
              Information about working days, weekend days, and list of public holidays from the requested date period and port.
              Possible APIs:
              **Port calendar**: Query about the companies that will work on a specific period of time.
              Request parameters: port name, port UN/LOCODE, name of the company, activity, selected period of time.
              Data included in the response: json with the name of the company, day of the selected period, opening hours on that day.
      parameters:
        - $ref: '#/components/parameters/portCode'
        - $ref: '#/components/parameters/activity'
        - $ref: '#/components/parameters/targetPeriodeCoded'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  portCalendar:
                    type: array
                    items:
                      $ref: '#/components/schemas/portCalendar'
                  requestedParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
                      activityCode:
                        $ref: './oiapComponents.yml#/components/schemas/activity'
                      targePeriodeCoded:
                        $ref: '#/components/schemas/targetPeriodeCoded'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'  

  /isWorkingDay:
    get:
      tags:
        - Port Calendar
      summary: Returns a boolean indicating if a requested periode is a working day for a company or a governmental body.
      description: >
              Answer to the question that if a specific day working day for a company or a governmental body. 
              Information about working days, weekend days, and list of public holidays from the requested date period and port.
      parameters:
        - $ref: '#/components/parameters/portCode'
        - $ref: '#/components/parameters/activity'
        - $ref: '#/components/parameters/targetPeriodeCoded'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  isWorkingDay:
                    type: array
                    items:
                      $ref: '#/components/schemas/isWorkingDay'
                  requestedParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
                      activityCode:
                        $ref: './oiapComponents.yml#/components/schemas/activity'
                      targePeriodeCoded:
                        $ref: '#/components/schemas/targetPeriodeCoded'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'  

components:
  parameters: 
    portCode:
      in: query
      name: portCode
      description: |
            Port UN/LOCODE
            Default value is Locode of Port what provides the services
            example: portCode=ESBCN        
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/portCode'
    activity:
      in: query
      name: Activity
      description: |
            tbd      
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/activity'
    targetPeriodeCoded:
      in: query    
      name: targetPeriodeCode
      description: ' '
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/targetPeriode'

  schemas:
    portCalendar: 
      description: ' '
      type: object
      allOf:
        - type: object 
          properties:
            startDate:  
              $ref: './oiapComponents.yml#/components/schemas/fromDate' 
      required:
        - startDate 

    targetPeriodeCoded: 
      description: 'Target periode.'
      type: object
      allOf:
        - type: object 
          properties:
            startDate:  
              $ref: './oiapComponents.yml#/components/schemas/fromDate'
            dateRange:
              $ref: './oiapComponents.yml#/components/schemas/dateRange'
      required:
        - startDate
        - dateRange 

    isWorkingDay: 
      description: 'Boolean indicating that is a working day or not.'
      type: boolean
      enum: [Yes, Not]
      example: Yes