openapi: '3.0.3'
info:
  version: '0.9.0-oas3'
  title: OIAP
  description: |
    **Open Info API para Puertos**


    This file contains all the APIs developed for the `Open Info API para Puertos` project for the **Port Calendar Domain** within the initiative Ports 4.0 form Puertos del Estado (ES).

  termsOfService: http://swagger.io/terms/
  license:
    name: CC0 1.0 Universal (CC0 1.0)
    url: https://creativecommons.org/publicdomain/zero/1.0/deed.es
  contact:
    name: OpenInfoAPI github
    url: https://github.com/portdebarcelona/OpenInfoAPI-Ports
tags:
  - name: Port Calendar
    description: "APIs related to the docummentary procedures of a port."
    externalDocs:
      description: Description 
      url: http://swagger.io/ 
servers:
  - url: https://raw.githubusercontent.com/portdebarcelona/OpenInfoAPI-Ports/develop/oasdefinitions
    description: Servidor server 

paths:
  /portCalendar:
    get:
      tags:
        - Port Calendar
      summary: Returns a list of working days and openning hours.
      description: >
              Information about working days, weekend days, and list of public holidays from the requested date period and port.
              Possible APIs:
              **Port calendar**: Query about the companies that will work on a specific period of time.
              Request parameters: port name, port UN/LOCODE, name of the company, activity, selected period of time.
              Data included in the response: json with the name of the company, day of the selected period, opening hours on that day.

    
              https://docs.getfestivo.com/docs/products/public-holidays-api/list-holidays 
              Parameters
                country	  yes	ISO 3166-1 alpha-2 country code from Countries section.	string	US
                year	    yes	4-digit year	int	2020
                month	    no	1 or 2 digit month identifier (MM or M)	int	06
                day	      no	1 or 2 digit day identifier (DD or D)	int	23
                language	no	ISO 639-1 language code (default: en). Please be notified not all countries have their holiday names available in different languages.	string	en
                before	  no	Return only holidays before given date (default: 0)	bool	1
                after	    no	Return only holidays after given date (default: 0)	bool	1
                between	  no	Return only holidays between dates (NOTE: for this option to work, please pass month, and day if desired, as array of values, months and days, e.g. &month=1&month=5 to get holidays between January and May)	bool	1
                public	  no	Return only public holidays	bool	1
                format	  no	Define return data format (available: json, xml)	string	json
                timezone	no	Convert start and end date and time according to passed timezone	string	Europe/London


              Response: 
                status	                    int	Status code for the response.
                query	                      object	Object containing passed query details
                requestId	                  string	Unique identifier of the request. Include this as reference when reporting issues.
                holidays.id	                string	Unique identifier for the holiday.
                holidays.name	              string	Name of the holiday or observance. Format: YYYY-MM-DD
                holidays.date	              date	Date that the holiday actually occurs. Format: YYYY-MM-DD
                holidays.observed	          date	Date that the holiday is observed on. Example, some countries move holidays that land on a weekend to the following Monday. Often times, this value may be the same as date.
                holidays.substitute	        bool	Substitute holiday is another working day off work that is designated to replace a public holiday.
                holidays.start	            datetime	Start date and time in specified timezone of the holiday. Alterable by timezone parameter. Format: YYYY-MM-DD HH:ii:ss
                holidays.end	              datetime	End date and time in specified timezone of the holiday. Alterable by timezone parameter. Format: YYYY-MM-DD HH:ii:ss
                holidays.type	              string	Specific holiday type that this holiday has been recognised as.
                holidays.public	            bool	Whether or not the holiday or observance is a public holiday.
                holidays.country	          string	ISO 3166-1 alpha-2 code for the country that the holiday is for.
                holidays.subdivisions	      array	Table containing ISO 3166-2 codes for states or provinces that the holiday is for.
                availableFilters.language	  array	Table containing 639-1 codes for supported holiday name translations.

                {
                  "holidays": [
                    {
                      "id": "20200101_7b8288babc5dd6fa3dd6520884b3ae9c",
                      "name": "New Year's Day",
                      "date": "2020-01-01",
                      "observed": "2020-01-01",
                      "substitute": false,
                      "start": "2020-01-01T00:00:00Z",
                      "end": "2020-01-01T23:59:59Z",
                      "type": "public",
                      "public": false,
                      "country": "US",
                      "subdivisions": []
                    },
                    {
                      "id: "20200104_57b934051701087f56f65a304638b6b7",
                      "name": "World Braille Day",
                      "date": "2020-01-04",
                      "observed": "2020-01-04",
                      "substitute": false,
                      "start": "2020-01-04T00:00:00Z",
                      "end": "2020-01-04T23:59:59Z",
                      "type": "observance",
                      "public": false,
                      "country": "US",
                      "subdivisions": []
                    },
                    ...
                  ]
                }


      parameters:
        - $ref: '#/components/parameters/portCode'
        - $ref: '#/components/parameters/activity'
        - $ref: '#/components/parameters/targetPeriodeCoded'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  portCalendar:
                    type: array
                    items:
                      $ref: '#/components/schemas/portCalendar'
                  requestedParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
                      activityCode:
                        $ref: './oiapComponents.yml#/components/schemas/activity'
                      targePeriodeCoded:
                        $ref: '#/components/schemas/targetPeriodeCoded'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'  

  /isWorkingDay:
    get:
      tags:
        - Port Calendar
      summary: Returns a boolean indicating if a requested periode is a working day for a company or a governmental body.
      description: >
              Answer to the question that if a specific day working day for a company or a governmental body. 
              Information about working days, weekend days, and list of public holidays from the requested date period and port.
      parameters:
        - $ref: '#/components/parameters/portCode'
        - $ref: '#/components/parameters/activity'
        - $ref: '#/components/parameters/targetPeriodeCoded'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  isWorkingDay:
                    type: array
                    items:
                      $ref: '#/components/schemas/isWorkingDay'
                  requestedParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
                      activityCode:
                        $ref: './oiapComponents.yml#/components/schemas/activity'
                      targePeriodeCoded:
                        $ref: '#/components/schemas/targetPeriodeCoded'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'  

components:
  parameters: 
    portCode:
      in: query
      name: portCode
      description: |
            Port UN/LOCODE
            Default value is Locode of Port what provides the services
            example: portCode=ESBCN        
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/portCode'
    activity:
      in: query
      name: Activity
      description: |
            tbd      
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/activity'
    targetPeriodeCoded:
      in: query    
      name: targetPeriodeCode
      description: ' '
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/targetPeriode'

  schemas:
    portCalendar: 
      description: ' '
      type: object
      allOf:
        - type: object 
          properties:
            startDate:  
              $ref: './oiapComponents.yml#/components/schemas/fromDate' 
      required:
        - startDate 

    targetPeriodeCoded: 
      description: 'Target periode.'
      type: object
      allOf:
        - type: object 
          properties:
            startDate:  
              $ref: './oiapComponents.yml#/components/schemas/fromDate'
            dateRange:
              $ref: './oiapComponents.yml#/components/schemas/dateRange'
      required:
        - startDate
        - dateRange 

    isWorkingDay: 
      description: 'Boolean indicating that is a working day or not.'
      type: boolean
      enum: [Yes, Not]
      example: Yes