openapi: '3.0.3'
info:
  version: '0.9.0-oas3'
  title: OIAP
  description: |
    **Open Info API para Puertos**


    This file contains all the APIs developed for the `Open Info API para Puertos` project for the **Port Directory Domain** within the initiative Ports 4.0 form Puertos del Estado (ES).

  termsOfService: http://swagger.io/terms/
  license:
    name: CC0 1.0 Universal (CC0 1.0)
    url: https://creativecommons.org/publicdomain/zero/1.0/deed.es
  contact:
    name: OpenInfoAPI github
    url: https://github.com/portdebarcelona/OpenInfoAPI-Ports
tags:
  - name: Port Directory
    description: "APIs related to the docummentary procedures of a port."
    externalDocs:
      description: Description 
      url: http://swagger.io/  
servers:
  - url: https://raw.githubusercontent.com/portdebarcelona/OpenInfoAPI-Ports/develop/oasdefinitions
    description: Servidor server 

paths:
  /companies:
    get:
      description: Get some overview data of all the companies from a port or all the companies that perform an specific activity.
      tags:
        - Port Directory
      parameters:
        - $ref: '#/components/parameters/portCode'
        - $ref: '#/components/parameters/activity' 
      responses:
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  companiesOverviewData:
                    type: array
                    items:
                      $ref: '#/components/schemas/companyOverviewData'
                  queryParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
                      activity:
                        $ref: './oiapComponents.yml#/components/schemas/activity'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/Error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/Error' 

  /companies/{companyName}:
    get:
      description: Get a company by its name or part of it without diacritics. At least three characters have to be included. 
      tags:
        - Port Directory
      parameters:
        - $ref: '#/components/parameters/portCode'
        - $ref: '#/components/parameters/searchTerm' 
      responses:
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  companyNames:  # Plural, because it is an array
                    type: array
                    items:
                      $ref: '#/components/schemas/companyData'
                  queryParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
                      companyName:
                        $ref: './oiapComponents.yml#/components/schemas/searchTerm'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/Error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/Error'  


  /companies/{companyVat}:
    get:
      description: Get a company by its vat number.
      tags:
        - Port Directory
      parameters:
        - $ref: '#/components/parameters/portCode'
        - $ref: '#/components/parameters/companyVat'
      responses:
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  companyFromVat:
                    $ref: '#/components/schemas/companyData'
                  queryParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
                      companyVat:
                        $ref: './oiapComponents.yml#/components/schemas/companyVat'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/Error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/Error'  

  /companies/activities:
    get:
      description: Get a list of all the possible activities for a company or governmental body.
      tags:
        - Port Directory
      parameters:
        - $ref: '#/components/parameters/portCode'
      responses:
        '200':
          description: Successful operation
          headers:
            oiapApiVersion:
              $ref: './oiapComponents.yml#/components/headers/oiapApiVersion'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  activities:
                    $ref: '#/components/schemas/activities'
                  queryParams:
                    type: object
                    properties:
                      portCode:
                        $ref: './oiapComponents.yml#/components/schemas/portCode'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/Error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/Error' 

components:
  parameters: 
    portCode:
      in: query
      name: portCode
      description: |
            Port UN/LOCODE
            Default value is Locode of Port what provides the services
            example: portCode=ESBCN        
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/portCode'

    companyName:
      in: query
      name: companyName
      description: Name of the company
      required: true
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/companyName'

    searchTerm:
      in: query
      name: searchTerm
      description: Part of the name of the company without diacritics
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/searchTerm'

    companyVat:
      in: query
      name: companyName
      description: Vat number of the company
      required: true
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/companyVat'

    activity:
      in: query
      name: activity
      description: Activity of a company
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/activity'

  schemas:
    companyOverviewData: 
      description: 'Basic information about a company.' 
      type: object
      allOf:
        - type: object 
          properties:
            companyName:
              $ref: './oiapComponents.yml#/components/schemas/companyName' 
            activities:  # array, because they can be more than one
              type: array
              items:
                $ref: './oiapComponents.yml#/components/schemas/activity'
            companyVat:
              $ref: './oiapComponents.yml#/components/schemas/companyVat'
          required:
            - activities
            - companyName

    companyData: 
      description: 'Detailled information about a company or a governmental body.' 
      type: object
      allOf:
        - type: object 
          properties:  
            activities:  # array, because theycan be more than one
              type: array
              items:
                $ref: './oiapComponents.yml#/components/schemas/activity'
            companyName:  
              $ref: './oiapComponents.yml#/components/schemas/companyName' 
            email:  
              $ref: './oiapComponents.yml#/components/schemas/email'
            phone:  
              $ref: './oiapComponents.yml#/components/schemas/phone'
            website:  
              $ref: './oiapComponents.yml#/components/schemas/uri'
            companyAddress:  
              $ref: './oiapComponents.yml#/components/schemas/address'
            openingHours:
              $ref: './oiapComponents.yml#/components/schemas/openingHours'             
            afterHours: # contact info for after hours  
              $ref: './oiapComponents.yml#/components/schemas/afterHours' 
            companyVat:  
              $ref: './oiapComponents.yml#/components/schemas/companyVat'
          required:
            - activities
            - companyName
            - phone

    activities:
      description: A list of all the possible activities for a company or governmental body..
      type: array
      items:
        $ref: './oiapComponents.yml#/components/schemas/activity'  
      example: [Port Authority, Harbour Master, Customs, Border Control Post (BCP), Immigration, Container Depot, Container Terminal, Container (CFS), General Cargo Terminal, Multi Purpose Terminal, Liquid Cargo Terminal, Bulk Cargo Terminal, Temperature Controlled Terminal, Dangerous Cargo Warehouse, Passenger Terminal, Inland Container Terminal, Liner Agent - Carrier, Railway Undertaking, Haulier, Barge Carrier, Freight Forwarder, Customs Broker, Stevedoring & Lashing, Tally, Ship Supplier, Nautic-technic, Tug, Mooring, Shipyards & Repair, Shipowner, Pilots, Research, Consulting, Port Community System - PCS, IT-Service, Insurance, Container Leasing, Railway Services, Railway Logistics Operator, Other]

