openapi: '3.0.3'
info:
  version: '0.9.0-oas3'
  title: Open Info API para Puertos (OIAP) Components
  description: 
    List of components that are used in the APIs developed for the Open Info API para Puertos project.
  license:
    name: CC0 1.0 Universal (CC0 1.0)
    url: https://creativecommons.org/publicdomain/zero/1.0/deed.es
  contact:
    name: OpenInfoAPI github
    url: https://github.com/portdebarcelona/OpenInfoAPI-Ports
# servers:
#  - url: https://github.com/portdebarcelona/OpenInfoAPI-Ports/blob/develop/oasdefinitions/
paths:
  /resADir:
    get:
      tags:
        - user
      summary: Logs out current logged in user session
      description: ''
      operationId: logoutUser
      responses:
        default:
          description: successful operation 
components:
  headers: 
    currentPage: 
        schema: 
            type: string
            example: fE9mZnNldHw9MCZsaW1pdD01
        description: A link to the current page.
        required: true
    nextPage: 
        schema:
            type: string
            example: fE9mZnNldHw9NSZsaW1pdD01
        description: A link to the next page. Next-Page header link MAY be omitted if the current page is the last page.
        required: false
    prevPage:
        schema: 
            type: string
            example: fE9mZnNldHw9MCZsaW1pdD01
        description: A link to the previous page. Previous-Page header link MAY be omitted if the current page is the first page.
        required: false
    lastPage: 
        schema: 
            type: string
            example: fE9mZnNldHw9NTkmbGltaXQ9NQ==
        description: A link to the last page. Last-Page header link MAY be omitted if the current page is the last page.
        required: false
    firstPage: 
        schema: 
            type: string
            example: fE9mZnNldHw9NjAmbGltaXQ9NQ==
        description: A link to thefirst page. First-Page header link MAY be omitted if current page is the first page.
        required: false
    apiVersion:
        schema: 
            type: string
            example: 0.9.0-oas3
        description: SemVer used to indicate the version of the contract (API version) returned.
  schemas:
    # Location components
    portCode:
      description: |
            Port UN/LOCODE
      type: string
      maxLength: 5
      example: ESBCN
    # Date and time components
    dateTime:  
      description: The datetime (day, hour, minute, second ) of the moment for which Air Quality Observed information is requested. The value is populated in ISO 8601 
      type: string
      format: date
      example: 2022-01-30T17:24:09Z
    WeatherObserved:
      description: 'An observation of weather conditions at a certain place and time. This data model has been developed in cooperation with mobile operators and the GSMA.'
      properties:
        address:
          # https://schema.org/address 
          description: 'The mailing address'
          properties:
            addressCountry:
              description: 'Property. The country. For example, Spain. Model:''https://schema.org/addressCountry'''
              type: string
            addressLocality:
              description: 'Property. The locality in which the street address is, and which is in the region. Model:''https://schema.org/addressLocality'''
              type: string
            addressRegion:
              description: 'Property. The region in which the locality is, and which is in the country. Model:''https://schema.org/addressRegion'''
              type: string
            postOfficeBoxNumber:
              description: 'Property. The post office box number for PO box addresses. For example, 03578. Model:''https://schema.org/postOfficeBoxNumber'''
              type: string
            postalCode:
              description: 'Property. The postal code. For example, 24004. Model:''https://schema.org/https://schema.org/postalCode'''
              type: string
            streetAddress:
              description: 'Property. The street address. Model:''https://schema.org/streetAddress'''
              type: string
          type: object
        airQualityIndex:
          # https://schema.org/Number
          description: 'Air quality index is a number used to report the quality of the air on any given day.'
          type: number
        airQualityIndexForecast:
          # https://schema.org/Number
          description: 'Forecasted overall Air Quality Index (AQI) over a certain duration in future.'
          type: number
        airTemperatureForecast:
          # https://schema.org/Number
          description: 'Forecasted value of air temperature over a certain duration in future.'
          type: number
        airTemperatureTSA:
          description: 'Object defining the temporal processing of a basic property during a period. It provides Maximum, minimum, instant value and average'
          properties:
            avgOverTime:
              type: number
            instValue:
              type: number
            maxOverTime:
              type: number
            minOverTime:
              type: number
          type: object
        alternateName:
          description: 'An alternative name for this item'
          type: string
        aqiMajorPollutant:
          description: 'Major pollutant in the Air Quality Index (AQI).'
          type: string
        aqiMajorPollutantForecast:
          description: 'Forecasted major air pollutant in the Air Quality Index (AQI) over a certain duration in future.'
          type: string
        areaServed:
          description: 'The geographic area where a service or offered item is provided'
          type: string
        atmosphericPressure:
          # x-ngsi: //  model: https://schema.org/Number //  type: Property  //  units: 'Hecto pascals'
          description: 'The atmospheric pressure observed measured in Hecto Pascals'
          minimum: 0
          type: number
        dataProvider:
          description: 'A sequence of characters identifying the provider of the harmonised data entity.'
          type: string
        dateCreated:
          description: 'Entity creation timestamp. This will usually be allocated by the storage platform.'
          format: date-time
        dateModified:
          description: 'Timestamp of the last modification of the entity. This will usually be allocated by the storage platform.'
          format: date-time
          type: string
        dateObserved:
          description: 'Date of the observed entity defined by the user.'
          format: date-time
          type: string
        description:
          description: 'A description of this item'
          type: string
        dewPoint:
          # x-ngsi:  // model: https://schema.org/Number  // type: Property  // units: 'Celsius degrees'
          description: 'The dew point encoded as a number. Observed temperature to which air must be cooled to become saturated with water vapor'
          type: number
        feelLikesTemperature:
          description: 'Temperature appreciation of the item'
          type: number
        feelsLikesTemperature:
          description: 'Temperature appreciation of the item'
          type: number
        gustSpeed:
          description: 'A sudden burst of high-speed wind over the observed average wind speed lasting only for a few seconds.'
          type: number
        id:
          anyOf: &weatherobserved_-_properties_-_owner_-_items_-_anyof
            - description: 'Property. Identifier format of any NGSI entity'
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
            - description: 'Property. Identifier format of any NGSI entity'
              format: uri
              type: string
          description: 'Unique identifier of the entity'
        illuminance:
          # x-ngsi: // type: Property  //  units: Lux
          description: 'Observed instantaneous ambient light intensity'
          type: number
        location:
          description: 'Geojson reference to the item. It can be Point, LineString, Polygon, MultiPoint, MultiLineString or MultiPolygon'
          oneOf:
            - description: 'Geoproperty. Geojson reference to the item. Point'
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    type: number
                  minItems: 2
                  type: array
                type:
                  enum:
                    - Point
                  type: string
              required:
                - type
                - coordinates
              title: 'GeoJSON Point'
              type: object
            - description: 'Geoproperty. Geojson reference to the item. LineString'
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    items:
                      type: number
                    minItems: 2
                    type: array
                  minItems: 2
                  type: array
                type:
                  enum:
                    - LineString
                  type: string
              required:
                - type
                - coordinates
              title: 'GeoJSON LineString'
              type: object
            - description: 'Geoproperty. Geojson reference to the item. Polygon'
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    items:
                      items:
                        type: number
                      minItems: 2
                      type: array
                    minItems: 4
                    type: array
                  type: array
                type:
                  enum:
                    - Polygon
                  type: string
              required:
                - type
                - coordinates
              title: 'GeoJSON Polygon'
              type: object
            - description: 'Geoproperty. Geojson reference to the item. MultiPoint'
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    items:
                      type: number
                    minItems: 2
                    type: array
                  type: array
                type:
                  enum:
                    - MultiPoint
                  type: string
              required:
                - type
                - coordinates
              title: 'GeoJSON MultiPoint'
              type: object
            - description: 'Geoproperty. Geojson reference to the item. MultiLineString'
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    items:
                      items:
                        type: number
                      minItems: 2
                      type: array
                    minItems: 2
                    type: array
                  type: array
                type:
                  enum:
                    - MultiLineString
                  type: string
              required:
                - type
                - coordinates
              title: 'GeoJSON MultiLineString'
              type: object
            - description: 'Geoproperty. Geojson reference to the item. MultiLineString'
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    items:
                      items:
                        items:
                          type: number
                        minItems: 2
                        type: array
                      minItems: 4
                      type: array
                    type: array
                  type: array
                type:
                  enum:
                    - MultiPolygon
                  type: string
              required:
                - type
                - coordinates
              title: 'GeoJSON MultiPolygon'
              type: object
          
        name:
          description: 'The name of this item.'
          type: string
        owner:
          description: 'A List containing a JSON encoded sequence of characters referencing the unique Ids of the owner(s)'
          items:
            anyOf: *weatherobserved_-_properties_-_owner_-_items_-_anyof
            description: 'Property. Unique identifier of the entity'
          type: array
        precipitation:
          description: 'Amount of water rain registered. Unis:''Liters per square meter''. '
          minimum: 0
          type: number
        precipitationForecast:
          description: 'Forecasted rainfall over a certain duration in future.'
          type: number
          x-ngsi:
        pressureTendency:
          description: 'Enum:''falling, raising, steady''. Is the pressure rising or falling? It can be expressed in quantitative terms or qualitative terms.'
          oneOf:
            - enum:
                - falling
                - raising
                - steady
              type: string
            - type: number
        refDevice:
          # x-ngsi: // model: https://schema.org/URL  // type: Relationship
          anyOf:
            - description: 'Property. Identifier format of any NGSI entity'
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
            - description: 'Property. Identifier format of any NGSI entity'
              format: uri
              type: string
          description: 'A reference to the device(s) which captured this observation.'
        refPointOfInterest:
          # x-ngsi: // model: https://schema.org/URL  // type: Relationship
          description: 'Point of interest related to the item'
          type: string
        relativeHumidity:
          description: 'Humidity in the Air. Observed instantaneous relative humidity (water vapour in air)'
          maximum: 1
          minimum: 0
          type: number
          x-ngsi:
            type: Property
        relativeHumidityForecast:
          description: 'Forecasted relative humidity (water vapour in air) over a certain duration in future'
          type: number
          x-ngsi:
            model: https://schema.org/Number
            type: Property
        seeAlso:
          description: 'list of uri pointing to additional resources about the item'
          oneOf:
            - items:
                format: uri
                type: string
              minItems: 1
              type: array
            - format: uri
              type: string
          x-ngsi:
            type: Property
        snowHeight:
          description: 'The snow height observed by generic snow depth measurement sensors, expressed in centimeters'
          minimum: 0
          type: number
          x-ngsi:
            model: https://schema.org/Number
            type: Property
            units: centimeters
        solarRadiation:
          description: 'The solar radiation observed measured in Watts per square'
          minimum: 0
          type: number
          x-ngsi:
            model: https://schema.org/Number
            type: Property
            units: w/m2
        source:
          description: 'A sequence of characters giving the original source of the entity data as a URL. Recommended to be the fully qualified domain name of the source provider, or the URL to the source object.'
          type: string
          x-ngsi:
            type: Property
        streamGauge:
          description: 'The water level surface elevation observed by Hydrometric measurement sensors, namely a [Stream Gauge](https://en.wikipedia.org/wiki/Stream_gauge) expressed in centimeters'
          minimum: 0
          type: number
          x-ngsi:
            model: https://schema.org/Number
            type: Property
            units: centimeters
        temperature:
          description: 'Temperature of the item'
          type: number
          x-ngsi:
            type: Property
        type:
          description: 'NGSI Entity type. It has to be WeatherObserved'
          enum:
            - WeatherObserved
          type: string
          x-ngsi:
            type: Property
        uVIndexMax:
          description: 'The maximum UV index for the period, based on the World Health Organization''s UV Index measure. [http://www.who.int/uv/intersunprogramme/activities/uv_index/en/](http://www.who.int/uv/intersunprogramme/activities/uv_index/en/) the values between 1 and 11 are the valid range for the index. The value 0 is for describing that no signal is detected so no value is stored.'
          minimum: 0
          type: number
          x-ngsi:
            model: https://schema.org/Number
            type: Property
        visibility:
          anyOf:
            - enum:
                - veryPoor
                - poor
                - moderate
                - good
                - veryGood
                - excellent
              type: string
            - minimum: 0
              type: number
          description: 'Categories of visibility'
          x-ngsi:
            model: http://schema.org/Text
            type: Property
        weatherType:
          description: 'Text description of the weather'
          type: string
          x-ngsi:
            model: http://schema.org/Text.
            type: Property
        windDirection:
          description: 'Direction of the wind bet'
          maximum: 360
          minimum: 0
          type: number
          x-ngsi:
            model: http://schema.org/Number
            type: Property
        windSpeed:
          description: 'Intensity of the wind'
          minimum: 0
          type: number
          x-ngsi:
            model: http//schema.org/Number
            type: Property
      required:
        - id
        - type
        - dateObserved
        - location
      type: object
      x-derived-from: ""
      x-disclaimer: 'Redistribution and use in source and binary forms, with or without modification, are permitted  provided that the license conditions are met. Copyleft (c) 2021 Contributors to Smart Data Models Program'
      x-license-url: https://github.com/smart-data-models/dataModel.Weather/blob/master/WeatherObserved/LICENSE.md
      x-model-schema: https://smart-data-models.github.io/dataModel.Weather/WeatherObserved/schema.json
      x-model-tags: IUDX
      x-version: 0.3.1