openapi: '3.0.3'
info:
  version: '1.0.0-oas3'
  title: OIAP
  description: 
    Open Info API para Puertos.  
    This file contains all the APIs developed for the Open Info API para Puertos project within the initiative Ports 4.0 form Puertos del Estado (ES).
    For this sample, you can use the api key
    `special-key` to test the authorization filters.  
  termsOfService: http://swagger.io/terms/
  license:
    name: CC0 1.0 Universal (CC0 1.0)
    url: https://creativecommons.org/publicdomain/zero/1.0/deed.es
  contact:
    name: OpenInfoAPI github
    url: https://github.com/portdebarcelona/OpenInfoAPI-Ports
tags:
  - name: Notices
    description: "APIs related to some notices of interest from a port."
    externalDocs:
      description: Description 
      url: http://swagger.io
servers:
  - url: https://raw.githubusercontent.com/portdebarcelona/OpenInfoAPI-Ports/develop/oasdefinitions
    description: Servidor server 
# Canvi efectuat: 'https://raw.githubusercontent.com/portdebarcelona/OpenInfoAPI-Ports/develop/oasdefinitions a '.
paths:
  /notices/subscriptionRequest: 
    post:
      tags:
        - Notices
      summary: Subscription request
      description: 'Request a subscription to a notices service from a port'
      operationId: subscriptionRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/subscriber'
        description: request placed for subscribing to a notices service
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema: # subscription response
                $ref: '#/components/schemas/subscriptionReference'
        '400':
          description: Invalid Order
  /notices/subscriptionValidation:
    post:
      tags:
        - Notices
      summary: Subscription validation
      description: 'Post the validation code received to fulfill the subscription request to a notices service from a port'
      operationId: subscriptionValidation
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/subscriptionRequestReference'
                - $ref: './oiapComponents.yml#/components/schemas/validationKey'
        description: request placed for validating the subscription to a notices service
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validationMessage'
        '400':
          description: Invalid Order
  /notices/unsubscriptionRequest: 
    post:
      tags:
        - Notices
      summary: Unsubscription request
      description: 'Request to cancel a subscription of a notices service from a port'
      operationId: unsubscriptionRequest
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: './oiapComponents.yml#/components/schemas/email'
                - $ref: './oiapComponents.yml#/components/schemas/phone'
              example: {"email": "name@domain.com"} 
        description: request placed for unsubscribing to a notices service
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema: # unsubscription response
                $ref: '#/components/schemas/unsubscriptionReference'

        '400':
          description: Invalid Order
  /notices/unsubscriptionValidation:
    post:
      tags:
        - Notices
      summary: Unsubscription validation
      description: 'Post the validation code received to cancel the subscription to a notices service from a port'
      operationId: unsubscriptionValidation
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/subscriptionRequestReference'
                - $ref: './oiapComponents.yml#/components/schemas/validationKey'
        description: request placed for validating the subscription to a notices service
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validationMessage'
        '400':
          description: Invalid Order
  /notices/notices:
    get:
      tags:
        - Notices
      summary: Returns a list of notices
      description: Returns a list of notices. The default value is a list of the active notices but notices that have expired can also be retrieved if the parameter 'publishingStage' is set to EXPIRED and the selection can be refined including the parameter 'fromDate'
      parameters:
        - $ref: '#/components/parameters/portCode'
        - $ref: '#/components/parameters/publishingStage'
        - $ref: '#/components/parameters/fromDate'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            apiVersion:
              $ref: './oiapComponents.yml#/components/headers/apiVersion'
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/notice'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'  
  /notices/noticesCategories:
    get:
      tags:
        - Notices
      summary: Returns a list of notices categories 
      description: >-
        This GET API returns the list of all the category names that a user can subscribe. 
        Please see the 'noticesCategories' attribute which returns an
        array of noticeCategories names. Each noticeCategories or a combination of noticeCategories can be
        searched using the syntax options shown below.
      parameters:
        - $ref: '#/components/parameters/portCode'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            apiVersion:
              $ref: './oiapComponents.yml#/components/headers/apiVersion'
          content: 
            application/json:
              schema:
                type: object 
                $ref: '#/components/schemas/noticesCategories'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
  /notices/noticesLanguages:
    get:
      tags:
        - Notices
      summary: List of the possible languages.
      description: Returns a list of the possible languages for the notices published.
      parameters:
        - $ref: '#/components/parameters/portCode'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            apiVersion:
              $ref: './oiapComponents.yml#/components/headers/apiVersion'
          content: 
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/noticesLanguages'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'
  /notices/notices/{id}:
    get:
      tags:
        - Notices
      summary: Returns a notice identified by its unique id.
      description: Returns a notice identified by its unique id.
      parameters:  
        - name: id
          in: path
          description: ID of a notice
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/portCode' 
      responses: #status code
        '200':
          description: Successful operation
          headers:
            apiVersion:
              $ref: './oiapComponents.yml#/components/headers/apiVersion'
          content: 
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/notice'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'  
components:
  parameters: 
    portCode:
      in: query
      name: portCode
      description: |
            Port UN/LOCODE
            Default value is Locode of Port what provides the services
            example: portCode=ESBCN        
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/portCode'
    publishingStage:  
      in: query
      name: publishingStage
      description: 
            The stage of the publishing process of a notice. There are only two possible stages, ACTIVE and EXPIRED. This parameter must be used when the publishing process is EXPIRED. If not provided, the ACTIVE stage is used by default.
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/publishingStage'
    fromDate:  
      in: query
      name: fromDate
      description: 
            The date (day) from the expired notices are requested. The value is populated in ISO 8601 Date format (eg. 2022-01-30). This parameter is only needed to retrieve the expired notices and to limit their number.
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/fromDate'
    id:  
      in: query
      name: id
      description: 
            The unique identification of a notice.
      required: false
      style: form
      explode: false
      schema:
        $ref: './oiapComponents.yml#/components/schemas/id'
  schemas:
    subscriber: # Object with all the information of a service subscriber (useful for News and Notices) 
      description: A subscriber identified by an email or a phone number.
      type: object
      allOf:
        - type: object
          properties:
            contactInfo:  # email or phone
              $ref: './oiapComponents.yml#/components/schemas/contactInfo'  
        - type: object
          properties:
            name:
              $ref: './oiapComponents.yml#/components/schemas/name' 
        - type: object
          properties:
            surname:
              $ref: './oiapComponents.yml#/components/schemas/surname' 
        - type: object
          properties:
            company: # company is an composite object with a companyName and a companyCode
              $ref: './oiapComponents.yml#/components/schemas/company' 
        - type: object
          properties:
            categories: # it must be an array of categories Can be the same for News and Notices?
              $ref: './oiapComponents.yml#/components/schemas/noticeCategory' 
        - type: object
          properties:
            language:
              $ref: './oiapComponents.yml#/components/schemas/language' 
      required: 
        - contactInfo
        - categories
        - language

    subscriptionReference:
      description: Response after a subscription request has been received
      type: object
      properties:
        subscriptionRequestReference:
          $ref: '#/components/schemas/subscriptionRequestReference'
        subscriptionRequestMessage:
          $ref: '#/components/schemas/subscriptionRequestMessage'
    subscriptionRequestReference: 
      type: string
      example: '2022-02-07T17:05:12_RZW256'
    subscriptionRequestMessage:
      type: string 
      example: 'Your subscription request has been received and soon you will receive a validation code (email/sms)'
    unsubscriptionRequestReference: 
      type: string
      example: '2022-02-10T17:05:12_RZT056'
    unsubscriptionRequestMessage:
      type: string 
      example: 'Your unsubscription request has been received and soon you will receive a validation code (email/sms)'
    unsubscriptionReference:
      description: Response after an unsubscription request has been received
      type: object
      allOf:
        - $ref: '#/components/schemas/unsubscriptionRequestReference'
        - $ref: '#/components/schemas/unsubscriptionRequestMessage'
    notice: # Aixo podria ser comu per a tot el domini, dient-se notice i, a la part del path, cridar aquest esquema o un array d'aquest esquema
      description: A notice from its unique id.
      type: object
      allOf:
        - type: object
          properties:
            id:
              $ref: './oiapComponents.yml#/components/schemas/id' 
        - type: object
          properties:
            language:
              $ref: './oiapComponents.yml#/components/schemas/language' 
        - type: object
          properties:
            subject:
              $ref: './oiapComponents.yml#/components/schemas/subject' 
        - type: object
          properties:
            content:
              $ref: './oiapComponents.yml#/components/schemas/content' 
        - type: object
          properties:
            category:
              $ref: './oiapComponents.yml#/components/schemas/noticeCategory' 
        - type: object
          properties:
            startTime:
              $ref: './oiapComponents.yml#/components/schemas/startTime' 
        - type: object
          properties:
            endTime:
              $ref: './oiapComponents.yml#/components/schemas/endTime' 
        - type: object
          properties:
            uri:
              $ref: './oiapComponents.yml#/components/schemas/uri'
      required: 
        - id
        - language
        - subject
        - startTime
    noticesCategories:
      description: A list of notices categories.
      type: array
      items:
        $ref: './oiapComponents.yml#/components/schemas/noticeCategory'
      example: ['Ship arrival', 'Ship departure', 'Sea state', 'Pollution warning', 'Traffic status', 'Terminal notices']
    noticesLanguages:
      description: A list of languages available for the notices.
      type: array
      items:
        $ref: './oiapComponents.yml#/components/schemas/noticeLanguage'  
      example: ['ca', 'es', 'en', 'fr']
    validationMessage:
      type: string 
      example: 'Your subscription request has been approved'



