openapi: '3.0.3'
info:
  version: '1.0.0'
  title: Open Info API para Puertos (OIAP) Components
  description: 
    List of components that are used in the APIs developed for the Open Info API para Puertos project.
  license:
    name: CC0 1.0 Universal (CC0 1.0)
    url: https://creativecommons.org/publicdomain/zero/1.0/deed.es
  contact:
    name: OpenInfoAPI github
    url: https://github.com/portdebarcelona/OpenInfoAPI-Ports
tags:
  - name: OIAP Components
    description: "List of components that are used in the APIs developed for the Open Info API para Puertos project."
servers:
  - url: https://api.server.test/v1   
paths:
  /nothing:
    get:
      responses:
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: './oiapComponents.yml#/components/schemas/error'
components:
  headers: 
    Current-Page: 
        schema: 
            type: string
            example: fE9mZnNldHw9MCZsaW1pdD01
        description: A link to the current page.
        required: true
    Next-Page: 
        schema:
            type: string
            example: fE9mZnNldHw9NSZsaW1pdD01
        description: A link to the next page. Next-Page header link MAY be omitted if the current page is the last page.
        required: false
    Prev-Page:
        schema: 
            type: string
            example: fE9mZnNldHw9MCZsaW1pdD01
        description: A link to the previous page. Previous-Page header link MAY be omitted if the current page is the first page.
        required: false
    Last-Page: 
        schema: 
            type: string
            example: fE9mZnNldHw9NTkmbGltaXQ9NQ==
        description: A link to the last page. Last-Page header link MAY be omitted if the current page is the last page.
        required: false
    First-Page: 
        schema: 
            type: string
            example: fE9mZnNldHw9NjAmbGltaXQ9NQ==
        description: A link to thefirst page. First-Page header link MAY be omitted if current page is the first page.
        required: false
    API-Version:
        schema: 
            type: string
            example: 1.0.0
        description: SemVer used to indicate the version of the contract (API version) returned.
  parameters: 
    portCode:
      in: query
      name: portCode
      description: |
            Port UN/LOCODE
            Default value is Locode of Port what provides the services
            example: portCode=ESBCN        
      required: false
      style: form
      explode: false
      schema:
        $ref: '#/components/schemas/portCode'
    startDate:  
      in: query
      name: startDate
      description: The start date of the period for which schedule information is requested. The value is populated in ISO 8601 Date format. If not provided, the current date is used by default.
      required: false
      style: form
      explode: false
      schema:
        $ref: '#/components/schemas/startDate'
    dateRange:  
      in: query
      name: dateRange
      description: The time period for which schedule information is sent. The duration is populated in ISO 8601 Duration format. If not provided, 24 hours is used by default.
      required: false
      style: form
      explode: false
      example: T24H
      schema:
        $ref: '#/components/schemas/dateRange'
    shipType:
      in: query
      name: shipType
      description:
            Type of ship 
            Default value are all types
      required: false
      style: form
      explode: false
      schema:
        $ref: '#/components/schemas/shipType'
  schemas:
    # Response components 
    shipArrivalForecast:
      description: list of ships that will arrive on a given period of time
      type: object
      allOf:
        - type: object
          properties:
            shipIMONumber:
              $ref: '#/components/schemas/shipIMONumber'
        - type: object
          properties:
            shipName:
              $ref: '#/components/schemas/shipName'
        - type: object
          properties:
            shipType:
              $ref: '#/components/schemas/shipType'
        - type: object
          properties:
            estimatedTimeOfArrival:
              $ref: '#/components/schemas/estimatedTimeOfArrival'
      required: 
        - shipIMONumber
        - shipName
        - shipType
        - estimatedTimeOfArrival
    shipInPort:
      description: list of ships that now are in Port
      type: object
      allOf:
        - type: object
          properties:
            shipIMONumber:
              $ref: '#/components/schemas/shipIMONumber'
        - type: object
          properties:
            shipName:
              $ref: '#/components/schemas/shipName'
        - type: object
          properties:
            shipType:
              $ref: '#/components/schemas/shipType'
        - type: object
          properties:
            actualTimeOfArrival:
              $ref: '#/components/schemas/actualTimeOfArrival'
        - type: object
          properties:
            estimatedTimeOfDeparture:
              $ref: '#/components/schemas/estimatedTimeOfDeparture'
        - type: object
          properties:
            berth:
              $ref: '#/components/schemas/berth'
        - type: object
          properties:
            lastPortOfCall:
              $ref: '#/components/schemas/lastPortOfCall'       
      required: 
        - shipIMONumber
        - shipName
        - shipType
        - actualTimeOfArrival
        - estimatedTimeOfDeparture    
    # Location components
    portCode:
      description: |
            Port UN/LOCODE
      type: string
      maxLength: 5
      example: ESBCN 
    lastPortOfCall:
      description: |
            UN/LOCODE of the last POrt of Call
      type: string
      maxLength: 5
      example: HKHKG 
    # Ship components
    shipIMONumber:
      type: string
      maxLength: 7 
      description: The identifier of ship.
      example: 9876543 
    shipName:
      type: string
      description: The ship’s name shown on the IMO ship’s certificates.
      maxLength: 35
      example: MSC GULSUN 
    shipType:
      description: |
            The type of the ship. The value is populated using the 3 character code from Annex 2 from UN/ECE Recommendation Nº28 when the means of transport is 1 (maritime).
            E.g.  505 Is the code  for a Carrier, general cargo/container. A vessel designed to carry general cargo and containers. 
      type: string
      maxLength: 3
      example: 505    
    # Date and time components
    startDate:  
      description: The start date of a period. The value is populated in ISO 8601 Date format.
      type: string
      format: date
      example: 2020-04-06
    dateRange: 
      description: 
            The duration of a time period. It is populated in ISO 8601 duration format. E.g. 4 weeks and 2 days is represented as P4W2D
      type: string
      format: iso8601
      example: P4W  
    estimatedTimeOfArrival:  
      description: The date and time the means of transport is estimated to arrive at a specified location (ETA), in ISO 8601 Date format.
      type: string
      format: date
      example: 2020-04-06
    actualTimeOfArrival:  
      description: The date and time the means of transport arrives at a specified location (ATA), in ISO 8601 Date format.
      type: string
      format: date
      example: 2020-04-06 06:00
    estimatedTimeOfDeparture:  
      description: The date and time the means of transport is estimated to depart from a specified location (ETD), in ISO 8601 Date format.
      type: string
      format: date
      example: 2020-04-08 12:00
    actualTimeOfDeparture:  
      description: The date and time the means of transport departs from a specified location (ATD), in ISO 8601 Date format.
      type: string
      format: date
      example: 2020-04-06 06:00      
    # Infrastructure components
    berth:
      type: object
      description: 
        Identification of a berth from a port.  
      properties:
        code:
          description: Berth code. Code assigned to a berth from a port.  
          type: string
        description:
          description: Berth name. 
          type: string
      required:
        - code
    # Error schemas
    error:
      type: object
      description: 
        Error body
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
