openapi: '3.0.3'
info:
  version: '1.0'
  title: API Ships Arrival Forecasts info
  description: 
    Forecast of ships that will arrive at a port in a given period of time. 
  license:
    name: CC0 1.0 Universal (CC0 1.0)
    url: https://creativecommons.org/publicdomain/zero/1.0/deed.es
  contact:
    name: OpenInfoAPI github
    url: https://github.com/portdebarcelona/OpenInfoAPI-Ports
tags:
  - name: Ships Arrival Forecasts details
    description: "Ships that will arrive at a port in a given period of time"
servers:
  - url: https://api.server.test/v1
  - url: https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN 
paths:
  /shipsArrival:
    get:
      summary: Returns a list of ships that will arrive at a port in a given period of time
      description: Returns a list of ships that will arrive at a port in a given period of time
      parameters:
        - $ref: '#/components/parameters/portCode'
        - $ref: '#/components/parameters/period'
        - $ref: '#/components/parameters/shipType'
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
                example: [ 1,2,3,4]
components:
  parameters: 
    portCode:
      in: query
      name: portCode
      description: |
            UN/LOCODE of Port
            example: portCode=ESBCN

            Default value is Locode of Port what provides the services
      required: false
      style: form
      explode: false
      schema:
        $ref: '#/components/schemas/portCode'
    period:
      in: query
      name: period
      description: |
            Requested period of time
            example: period=ESBCN

            Default value is the present day
      required: false
      style: form
      explode: false
      schema:
        $ref: '#/components/schemas/period'    
    shipType:
      in: query
      name: shipType
      description:
            Type of ships
            Default value are all types
      required: false
      style: form
      explode: false
      schema:
        $ref: '#/components/schemas/shipType'
  schemas:
    portCode:
      description: |
            UN/LOCODE of Port
            example: portCode=ESBCN

            Default value is Locode of Port what provides the services
      type: string
      maxLength: 5
      example: ESBCN
    period:
      description: |
            Requested period of time
            example: period=ESBCN

            Default value is the present day
      type: string
      maxLength: 15
      example: ESBCN    
    shipType:
      description: |
            Requested period of time
            example: period=ESBCN

            Default value is the present day
      type: string
      maxLength: 15
      example: ESBCN     
      type: object
      $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.1.0#/components/parameters/vesselIMONumber'