openapi: '3.0.3'
info:
  version: '1.0'
  title: API Ships Arrival Forecasts info
  description: 
    Forecast of ships that will arrive at a port in a given period of time. 
  license:
    name: CC0 1.0 Universal (CC0 1.0)
    url: https://creativecommons.org/publicdomain/zero/1.0/deed.es
  contact:
    name: OpenInfoAPI github
    url: https://github.com/portdebarcelona/OpenInfoAPI-Ports
tags:
  - name: Ships Arrival Forecasts details
    description: "Ships that will arrive at a port in a given period of time"
servers:
  - url: https://api.server.test/v1
  - url: https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN 
paths:
  /shipsSchedulled:
    get:
      summary: Returns a list of ships that will arrive at a port in a given period of time
      description: Returns a list of ships that will arrive at a port in a given period of time
      parameters:
        - $ref: '#/components/parameters/portCode'
        - $ref: '#/components/parameters/startDate'
        - $ref: '#/components/parameters/dateRange'
        - $ref: '#/components/parameters/shipType'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            API-Version:
              $ref: '#/components/headers/API-Version'
            Current-Page:
              $ref: '#/components/headers/Current-Page'
            Next-Page:
              $ref: '#/components/headers/Next-Page'
            Prev-Page:
              $ref: '#/components/headers/Prev-Page'
            Last-Page:
              $ref: '#/components/headers/Last-Page'
            First-Page:
              $ref: '#/components/headers/First-Page'
          content: 
            application/json:
              schema:
                type: array
                items:
                  anyOf:
                    - $ref: '#/components/schemas/shipArrivalForecast'
              example: 
                oneOf:
                  vesselIMONumber: 1234567
                  vesselName: ALLURE OF THE SEAS
                  estimatedTimeOfArrival: 2022-01-21 08:05
        default:
          description: Unexpected error
          headers:
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'                
components:
  headers: 
    Current-Page: 
        schema: 
            type: string
            example: fE9mZnNldHw9MCZsaW1pdD01
        description: A link to the current page.
        required: true
    Next-Page: 
        schema:
            type: string
            example: fE9mZnNldHw9NSZsaW1pdD01
        description: A link to the next page. Next-Page header link MAY be omitted if the current page is the last page.
        required: false
    Prev-Page:
        schema: 
            type: string
            example: fE9mZnNldHw9MCZsaW1pdD01
        description: A link to the previous page. Previous-Page header link MAY be omitted if the current page is the first page.
        required: false
    Last-Page: 
        schema: 
            type: string
            example: fE9mZnNldHw9NTkmbGltaXQ9NQ==
        description: A link to the last page. Last-Page header link MAY be omitted if the current page is the last page.
        required: false
    First-Page: 
        schema: 
            type: string
            example: fE9mZnNldHw9NjAmbGltaXQ9NQ==
        description: A link to thefirst page. First-Page header link MAY be omitted if current page is the first page.
        required: false
    API-Version:
        schema: 
            type: string
            example: 1.0.0
        description: SemVer used to indicate the version of the contract (API version) returned.
  parameters: 
    ##################
    # Query parameters
    ##################
    portCode:
      in: query
      name: portCode
      description: |
            Port UN/LOCODE
            Default value is Locode of Port what provides the services
            example: portCode=ESBCN        
      required: false
      style: form
      explode: false
      schema:
        $ref: '#/components/schemas/portCode'
    startDate:  
      in: query
      name: startDate
      description: The start date of the period for which schedule information is requested. The value is populated in ISO 8601 Date format. If not provided, the current date is used by default.
      required: false
      schema:
        $ref: '#/components/schemas/startDate'
    dateRange:  
      in: query
      name: dateRange
      description: The time period for which schedule information is sent. The duration is populated in ISO 8601 Duration format.
      required: false
      schema:
        $ref: '#/components/schemas/dateRange'
    shipType:
      in: query
      name: shipType
      description:
            Type of ships
            Default value are all types
      required: false
      style: form
      explode: false
      schema:
        $ref: '#/components/schemas/shipType'
  schemas:
    portCode:
      description: |
            Port UN/LOCODE
      type: string
      maxLength: 5
      example: ESBCN 
    startDate:  
      description: The start date of the period for which schedule information is sent. The value is populated in ISO 8601 Date format.
      type: string
      format: date
      example: 2020-04-06
    dateRange: 
      description: 
            The time period for which schedule information is sent. The duration is populated in ISO 8601 Duration format.
      type: string
      format: iso8601
      example: P4W
    shipType:
      description: |
            Type of vessel
      type: string
      maxLength: 15
      example: ESBCN     
      $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.1.0#/components/parameters/vesselIMONumber'
    shipArrivalForecast:
      description: list of ships that will arrive on a given period of time
      type: object
      allOf:
        - type: object
          properties:
            vesselIMONumber:
              $ref: '#/components/schemas/vesselIMONumber'
        - type: object
          properties:
            vesselName:
              $ref: '#/components/schemas/vesselName'
        - type: object
          properties:
            estimatedTimeOfArrival:
              $ref: '#/components/schemas/estimatedTimeOfArrival'
      required: 
        - vesselIMONumber
        - vesselName
        - estimatedTimeOfArrival
      example: nom del vaixell
    vesselIMONumber:
      type: string
      description: https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.1.0#/components/parameters/vesselIMONumber
      maxLength: 7 
    vesselName:
      type: string
      description: https://app.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.2#/components/schemas/vesselName
      maxLength: 35 
    estimatedTimeOfArrival:  
      description: The date and time the ship is estimated to arrive at a specified location (ETA), in ISO 8601 Date format.
      type: string
      format: date
      example: 2020-04-06
    error: 
      description: 
            The time period for which schedule information is sent. The duration is populated in ISO 8601 Duration format.
      type: string
      format: iso8601
      example: P4W