openapi: '3.0.3'
info:
  version: '1.0.0'
  title: API Vessels in Port info
  description: 
    Vessels that are anchored/moored in the port. 
  license:
    name: CC0 1.0 Universal (CC0 1.0)
    url: https://creativecommons.org/publicdomain/zero/1.0/deed.es
  contact:
    name: OpenInfoAPI github
    url: https://github.com/portdebarcelona/OpenInfoAPI-Ports
tags:
  - name: Vessels in Port details
    description: "Vessels that are anchored/moored in the port."
servers:
  - url: https://api.server.test/v1
paths:
  /shipsInPort:
    get:
      summary: Returns a list of ships that are anchored or moored now in a Port.
      description: Returns a list of ships that are anchored or moored now in a Port.
      parameters:
        - $ref: '#/components/parameters/portCode'
      responses: #status code
        '200':
          description: Successful operation
          headers:
            API-Version:
              $ref: '#/components/headers/API-Version'
            Current-Page:
              $ref: '#/components/headers/Current-Page'
            Next-Page:
              $ref: '#/components/headers/Next-Page'
            Prev-Page:
              $ref: '#/components/headers/Prev-Page'
            Last-Page:
              $ref: '#/components/headers/Last-Page'
            First-Page:
              $ref: '#/components/headers/First-Page'
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/shipInPort'
        default:
          description: Unexpected error
          headers:
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'                
components:
  headers: 
    Current-Page: 
        schema: 
            type: string
            example: fE9mZnNldHw9MCZsaW1pdD01
        description: A link to the current page.
        required: true
    Next-Page: 
        schema:
            type: string
            example: fE9mZnNldHw9NSZsaW1pdD01
        description: A link to the next page. Next-Page header link MAY be omitted if the current page is the last page.
        required: false
    Prev-Page:
        schema: 
            type: string
            example: fE9mZnNldHw9MCZsaW1pdD01
        description: A link to the previous page. Previous-Page header link MAY be omitted if the current page is the first page.
        required: false
    Last-Page: 
        schema: 
            type: string
            example: fE9mZnNldHw9NTkmbGltaXQ9NQ==
        description: A link to the last page. Last-Page header link MAY be omitted if the current page is the last page.
        required: false
    First-Page: 
        schema: 
            type: string
            example: fE9mZnNldHw9NjAmbGltaXQ9NQ==
        description: A link to thefirst page. First-Page header link MAY be omitted if current page is the first page.
        required: false
    API-Version:
        schema: 
            type: string
            example: 1.0.0
        description: SemVer used to indicate the version of the contract (API version) returned.
  parameters: 
    ##################
    # Query parameters
    ##################
    portCode:
      in: query
      name: portCode
      description: |
            Port UN/LOCODE
            Default value is Locode of Port what provides the services
            example: portCode=ESBCN        
      required: false
      style: form
      explode: false
      schema:
        $ref: '#/components/schemas/portCode'
  schemas:
    shipInPort:
      description: list of ships that now are in Port
      type: object
      allOf:
        - type: object
          properties:
            shipIMONumber:
              $ref: '#/components/schemas/shipIMONumber'
        - type: object
          properties:
            shipName:
              $ref: '#/components/schemas/shipName'
        - type: object
          properties:
            shipType:
              $ref: '#/components/schemas/shipType'
        - type: object
          properties:
            actualTimeOfArrival:
              $ref: '#/components/schemas/actualTimeOfArrival'
        - type: object
          properties:
            estimatedTimeOfDeparture:
              $ref: '#/components/schemas/estimatedTimeOfDeparture'
        - type: object
          properties:
            berth:
              $ref: '#/components/schemas/berth'
        - type: object
          properties:
            lastPortOfCall:
              $ref: '#/components/schemas/lastPortOfCall'       
      required: 
        - shipIMONumber
        - shipName
        - shipType
        - actualTimeOfArrival
        - estimatedTimeOfDeparture
    shipIMONumber:
      type: string
      maxLength: 7 
      description: The identifier of ship for which schedule details are published.
      example: 9876543 
    shipName:
      type: string
      description: The ship’s name shown on the IMO ship’s certificates.
      maxLength: 35
      example: MSC GULSUN 
    actualTimeOfArrival:  
      description: The date and time the ship is estimated to arrive at a specified location (ETA), in ISO 8601 Date format.
      type: string
      format: date
      example: 2020-04-06 06:00
    estimatedTimeOfDeparture:  
      description: The date and time the ship is estimated to arrive at a specified location (ETA), in ISO 8601 Date format.
      type: string
      format: date
      example: 2020-04-08 12:00
    berth:
      type: object
      description: 
        Berth 
      properties:
        code:
          type: string
        description:
          type: string
      required:
        - code
    portCode:
      description: |
            Port UN/LOCODE
      type: string
      maxLength: 5
      example: ESBCN 
    lastPortOfCall:
      description: |
            UN/LOCODE of the last POrt of Call
      type: string
      maxLength: 5
      example: HKHKG 
    shipType:
      description: |
            The type of the ship shown on its IMO ship's certificate.
      type: string
      maxLength: 15
      example: CONTAINERSHIP  
    error:
      type: object
      description: 
        Error body
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
